name: Convert PDF to Base64 and Print

on:
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Download PDF (Compendium JBMO)
        run: curl -L -o CompendiumJBMO.pdf "http://www.toomates.net/biblioteca/CompendiumJBMO.pdf"

      - name: Convert to Base64 and print
        run: |
          base64 CompendiumJBMO.pdf > base64.txt
          echo "===== START OF BASE64 ====="
          cat base64.txt
          echo "===== END OF BASE64 ====="
